# -*- coding: utf-8 -*-
"""sistem panen (TTS 4)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c7kweZlHdYf5DXllajfm_2lePAEjb06x
"""

# main.py
def hitung_total_panen(panen_pagi, panen_sore):
    return panen_pagi + panen_sore

if __name__ == "__main__":
    total = hitung_total_panen(150, 77)
    print(f"Total Hasil Panen: {total} kg")