# -*- coding: utf-8 -*-
"""sistem panen (TTS 4)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c7kweZlHdYf5DXllajfm_2lePAEjb06x
"""

hasil_panen = [100, 150, 200, 175]

total = sum(hasil_panen)

print("Total hasil panen:", total, "kg")


def hitung_diskon(total, diskon):
    return total - (total * diskon / 100)


harga_total = 1000000
diskon = 10

harga_setelah_diskon = hitung_diskon(harga_total, diskon)

print("Harga setelah diskon:", harga_setelah_diskon)